/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUIdVocabRouteImport } from './routes/_auth/u/$id/vocab'
import { Route as AuthUIdDashboardRouteImport } from './routes/_auth/u/$id/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUIdVocabRoute = AuthUIdVocabRouteImport.update({
  id: '/u/$id/vocab',
  path: '/u/$id/vocab',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUIdDashboardRoute = AuthUIdDashboardRouteImport.update({
  id: '/u/$id/dashboard',
  path: '/u/$id/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$id/dashboard': typeof AuthUIdDashboardRoute
  '/u/$id/vocab': typeof AuthUIdVocabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u/$id/dashboard': typeof AuthUIdDashboardRoute
  '/u/$id/vocab': typeof AuthUIdVocabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/u/$id/dashboard': typeof AuthUIdDashboardRoute
  '/_auth/u/$id/vocab': typeof AuthUIdVocabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/u/$id/dashboard' | '/u/$id/vocab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u/$id/dashboard' | '/u/$id/vocab'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/u/$id/dashboard'
    | '/_auth/u/$id/vocab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/u/$id/vocab': {
      id: '/_auth/u/$id/vocab'
      path: '/u/$id/vocab'
      fullPath: '/u/$id/vocab'
      preLoaderRoute: typeof AuthUIdVocabRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/u/$id/dashboard': {
      id: '/_auth/u/$id/dashboard'
      path: '/u/$id/dashboard'
      fullPath: '/u/$id/dashboard'
      preLoaderRoute: typeof AuthUIdDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthUIdDashboardRoute: typeof AuthUIdDashboardRoute
  AuthUIdVocabRoute: typeof AuthUIdVocabRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUIdDashboardRoute: AuthUIdDashboardRoute,
  AuthUIdVocabRoute: AuthUIdVocabRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
